### ISSUE TITLE
Doesn't work on Python 3.12

### ISSUE THREAD

**Issue by sirkonst** [tonybaloney/perflint#44]
When I run `perflint` for my code on Python 3.12 I got a lot of errors related to astroid for example:

```
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'
```

In additional, `perflint` is not compatible with [pylint 3.x](https://github.com/tonybaloney/perflint/blob/c07391c17671c3c9d5a7fd69120d1f570e268d58/pyproject.toml#L11C4-L11C4).

**Comment by jenstroeger** [comment]
> In additional, `perflint` is not compatible with [pylint 3.x](https://github.com/tonybaloney/perflint/blob/c07391c17671c3c9d5a7fd69120d1f570e268d58/pyproject.toml#L11C4-L11C4).

See also:

- issue https://github.com/tonybaloney/perflint/issues/45
- PR https://github.com/tonybaloney/perflint/pull/46

**Comment by tonybaloney** [comment]
Fixed in 0.8.0
